/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/App'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiComponentRouteImport } from './routes/ui.$component'
import { Route as BlocksBlockRouteImport } from './routes/blocks.$block'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/App',
  path: '/App',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiComponentRoute = UiComponentRouteImport.update({
  id: '/ui/$component',
  path: '/ui/$component',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksBlockRoute = BlocksBlockRouteImport.update({
  id: '/$block',
  path: '/$block',
  getParentRoute: () => BlocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/components': typeof ComponentsRoute
  '/installation': typeof InstallationRoute
  '/why': typeof WhyRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/ui/$component': typeof UiComponentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/components': typeof ComponentsRoute
  '/installation': typeof InstallationRoute
  '/why': typeof WhyRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/ui/$component': typeof UiComponentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/components': typeof ComponentsRoute
  '/installation': typeof InstallationRoute
  '/why': typeof WhyRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/ui/$component': typeof UiComponentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/App'
    | '/about'
    | '/blocks'
    | '/components'
    | '/installation'
    | '/why'
    | '/blocks/$block'
    | '/ui/$component'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/App'
    | '/about'
    | '/blocks'
    | '/components'
    | '/installation'
    | '/why'
    | '/blocks/$block'
    | '/ui/$component'
  id:
    | '__root__'
    | '/'
    | '/App'
    | '/about'
    | '/blocks'
    | '/components'
    | '/installation'
    | '/why'
    | '/blocks/$block'
    | '/ui/$component'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AboutRoute: typeof AboutRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  InstallationRoute: typeof InstallationRoute
  WhyRoute: typeof WhyRoute
  UiComponentRoute: typeof UiComponentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/$component': {
      id: '/ui/$component'
      path: '/ui/$component'
      fullPath: '/ui/$component'
      preLoaderRoute: typeof UiComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$block': {
      id: '/blocks/$block'
      path: '/$block'
      fullPath: '/blocks/$block'
      preLoaderRoute: typeof BlocksBlockRouteImport
      parentRoute: typeof BlocksRoute
    }
  }
}

interface BlocksRouteChildren {
  BlocksBlockRoute: typeof BlocksBlockRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksBlockRoute: BlocksBlockRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AboutRoute: AboutRoute,
  BlocksRoute: BlocksRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  InstallationRoute: InstallationRoute,
  WhyRoute: WhyRoute,
  UiComponentRoute: UiComponentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
